// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnEnB82PuaxkxDyX2GzvMZnc4B_kcGVcc',
    appId: '1:242459047992:web:242c6cd085bd19cf318ecd',
    messagingSenderId: '242459047992',
    projectId: 'minichatapp-200f9',
    authDomain: 'minichatapp-200f9.firebaseapp.com',
    storageBucket: 'minichatapp-200f9.firebasestorage.app',
      databaseURL: "https://minichatapp-200f9-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA_BerweQoLheKP8aRq7w65XoO4IKq7hU',
    appId: '1:242459047992:android:598b2ee266fcd5ef318ecd',
    messagingSenderId: '242459047992',
    projectId: 'minichatapp-200f9',
    storageBucket: 'minichatapp-200f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTg5H5zV4KuqwFmXQ3zJ7gPEAKa3ffX1Y',
    appId: '1:242459047992:ios:d0b5b7a36cdc63f4318ecd',
    messagingSenderId: '242459047992',
    projectId: 'minichatapp-200f9',
    storageBucket: 'minichatapp-200f9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTg5H5zV4KuqwFmXQ3zJ7gPEAKa3ffX1Y',
    appId: '1:242459047992:ios:d0b5b7a36cdc63f4318ecd',
    messagingSenderId: '242459047992',
    projectId: 'minichatapp-200f9',
    storageBucket: 'minichatapp-200f9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnEnB82PuaxkxDyX2GzvMZnc4B_kcGVcc',
    appId: '1:242459047992:web:710db28dfc0d4929318ecd',
    messagingSenderId: '242459047992',
    projectId: 'minichatapp-200f9',
    authDomain: 'minichatapp-200f9.firebaseapp.com',
    storageBucket: 'minichatapp-200f9.firebasestorage.app',
  );
}
